line-length = 120
target-version = "py311"

[lint]
select = ["YTT", "ANN", "ASYNC", "S102", "S110", "S112", "S113", "S306", "S506", "S602", "S604", "S605", "BLE", "FBT", "B", "A", "COM818", "C4", "DTZ", "T10", "DJ", "FIX", "FA", "INT", "ISC", "ICN", "LOG", "G", "INP", "PIE", "T20", "PT", "Q", "RSE", "RET", "SLF", "SIM", "SLOT", "TID", "TD", "TC", "ARG", "PTH", "FLY", "I", "C90", "NPY", "PD", "N", "PERF", "E", "W", "F", "PGH", "PL", "PLC", "PLR", "PLE", "PLW", "UP", "FURB", "RUF", "TRY", "S", "DOC"]
ignore = ["ASYNC109", "TD002", "TD003", "TC006", "TC007",  "TRY003", "DOC", "UP044"]

[lint.pydocstyle]
convention = "pep257"

[format]
docstring-code-format = true
